### ISSUE TITLE
Undefined array key "disk"

### ISSUE THREAD

**Issue by mstfkhazaal** [awcodes/filament-curator#174]
When i use  Curation Blade Component
`<x-curator-curation :media="3" class="h-10" curation="thumbnail" />
`
i get this error `Undefined array key "disk"`

@awcodes

**Comment by awcodes** [comment]
Did you actually make a curation for the image?

**Comment by mstfkhazaal** [comment]
> Did you actually make a curation for the image?
I installed curation like in this video and with use documentation
https://www.youtube.com/watch?v=HMTtpsVX2mo

Upload image is work perfectly
![image](https://user-images.githubusercontent.com/47450090/237009190-4f1d997c-d49a-41ec-aa5a-a9d13f42920f.png)

but when i use curation blade component i get this error
 <x-curator-curation :media="3" curation="thumbnail" /> 
 
 https://drive.google.com/file/d/17HdTgKeGToH00L3FdVJVnbOPl7cgLSNZ/view?usp=sharing

**Comment by awcodes** [comment]
Right, but did you actually create the curation.? That's what I'm asking.
![Screen Shot 2023-05-09 at 8 38 40 AM](https://github.com/awcodes/filament-curator/assets/3596800/6f4ed3cf-1169-43f0-9bbd-ed8f0f9172a6)

**Comment by mstfkhazaal** [comment]
> Right, but did you actually create the curation.? That's what I'm asking. ![Screen Shot 2023-05-09 at 8 38 40 AM](https://user-images.githubusercontent.com/3596800/237095635-6f4ed3cf-1169-43f0-9bbd-ed8f0f9172a6.png)

Yes is work. 
but how can use blade component without curation 
If you are forced to curation 
How can upload picture directly to curation?

**Comment by awcodes** [comment]
You don't need curations unless you need to set a focal point on an image at a specific size.

Otherwise, use the [glider](https://github.com/awcodes/filament-curator#glider-blade-component) component to output the sizes you need on the fly in your blade file. That way they get cached and you don't need to have multiple copies of the files at different sizes taking up space on your server when they are not being used.

**Comment by mstfkhazaal** [comment]
Thanks
