### ISSUE TITLE
Tons of errors in log file if file doesn't exist on disk

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-curator#250]
Hello. If the file doesn't exist on disk, i have a big log file with errors
`Could not find the image 'public/media/ccc001c5-1175-41e7-814c-9b6af2dc39e6.png'`

full log https://pastebin.com/HYRmb90Y

Thanks.

**Comment by awcodes** [comment]
Is this happening with any disk or just s3 disks?

**Comment by lotarbo** [comment]
@awcodes, sorry, i dont know about s3, i use local disks only

**Comment by awcodes** [comment]
Ok. I'm surprise exists is logging. But see if I can find time today to replicate and explore.

**Comment by awcodes** [comment]
Ok, after some digging, this is an exception being thrown by Glide, and it makes sense. Unfortunately, since it is part of a dependency there is not much that can be done about it from the plugin.

You could either submit a PR to their package, but as it's there for a reason, I doubt they would change it. Your other option is to update the missing image in your record to one that exists or upload a new file to replace the missing one.
